import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import Table from '../components/Table'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='md:flex p-5 bg-slate-600'>
        <Card/>
        <Card/>
        <Card/>
      </div>

    <Table/>

    </div>
  )
}
