import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import Table from '../components/Table'
import CallToAction from '../components/CallToAction'
import ScrollToTop from "react-scroll-to-top";
import { BsFillArrowUpCircleFill } from 'react-icons/bs'

export default function Home({dark}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={`md:flex p-5 ${
            dark === "true"
              ? "bg-slate-600 text-white"
              : "bg-gray-100 text-black"
          }`}>
        <Card dark={dark} />
        <Card dark={dark} />
        <Card dark={dark} />
      </div>

    <Table dark={dark}/>
    <CallToAction dark={dark}/>
    <ScrollToTop smooth className='flex justify-center items-center hover:bg-gray-200'/>

    </div>
    
  )
}
